-- IntelliCoach Database Schema
-- Time-Tracking System with Start/Stop Functionality
-- SQLite database schema

-- Users table
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Activity Sessions table (Core time-tracking)
-- Stores each Start/Stop session with duration
CREATE TABLE IF NOT EXISTS activity_sessions (
    session_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    duration_minutes INTEGER,
    session_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    CHECK (activity_type IN ('Academic', 'Sport', 'Entertainment', 'Extra Activity', 'Sleep', 'Health / Hygiene'))
);

-- Recommended time allocations (reference data)
CREATE TABLE IF NOT EXISTS recommended_times (
    activity_type VARCHAR(50) PRIMARY KEY,
    min_minutes INTEGER NOT NULL,
    max_minutes INTEGER NOT NULL,
    description TEXT
);

-- User recommendations (generated by system)
CREATE TABLE IF NOT EXISTS recommendations (
    recommendation_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    recommendation_text TEXT NOT NULL,
    recommendation_type VARCHAR(50) NOT NULL,
    priority VARCHAR(20) DEFAULT 'MEDIUM',
    based_on_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Insert recommended time allocations
INSERT OR REPLACE INTO recommended_times (activity_type, min_minutes, max_minutes, description) VALUES 
('Academic', 360, 480, 'Study, homework, classes - 6 to 8 hours per day'),
('Sleep', 420, 540, 'Essential rest - 7 to 9 hours per day'),
('Sport', 60, 120, 'Physical exercise - 1 to 2 hours per day'),
('Entertainment', 60, 120, 'Leisure, games, social media - 1 to 2 hours per day'),
('Extra Activity', 60, 120, 'Clubs, volunteering, hobbies - 1 to 2 hours per day'),
('Health / Hygiene', 30, 60, 'Personal care, meals - 30 to 60 minutes per day');

-- Insert sample test user
INSERT OR IGNORE INTO users (user_id, username, email, password, full_name) VALUES 
(1, 'testuser', 'test@example.com', 'password123_encoded', 'Test User');

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_sessions_user_date ON activity_sessions(user_id, session_date);
CREATE INDEX IF NOT EXISTS idx_sessions_active ON activity_sessions(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_recommendations_user ON recommendations(user_id, created_at);